version: '3.8'

services:
  app:
    image: contacts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/contact
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: admin
#    depends_on:
#      - db
    restart: always

#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: contact
#    ports:
#      - "3307:3306"
#    volumes:
#      - db-data:/var/lib/mysql
#
#volumes:
#  db-data:
